### PR TITLE
Fix reflection based destructuring for redefined property

### LINKED ISSUE #343: Exception with redefined property(new modifier) stops enrichment altogether
### Describe the feature

Not sure if this eve belongs here, but I'm having trouble getting this package to work with ApplicationInsights sink. I'm trying to get deconstructed Refit.ValidationApiException but no luck.

Any help would be appreciated

### PR DESCRIPTION
**Pull request by krajek**
I may prepare another fix to tackle the problem of gathering properties from a type taking into account possible redefinitions.
However, I consider the change proposed here good practice for library robustness.

Fixes #343

### CODE REVIEW

**Comment by krajek** [comment]
@RehanSaeed if you think this is good, please release a new version, I lost track of how to do that :-).

File: Source/Serilog.Exceptions/Core/ExceptionPropertiesBag.cs [hunk 1]
```diff
@@ -56,10 +56,45 @@ public void AddProperty(string key, object? value)
...
+#if !NET5_0
+        /// <summary>
+        /// We want to be as robust as possible
+        /// so even in case of multiple properties with the same name
+        /// we want to at least try carrying on and keep working.
+        /// </summary>
+        private string MakeSureKeyIsUnique(string key)
+        {
+            var i = 0;
+            while (this.properties.ContainsKey(key) && i < 5)
```
Comment (domagojmedo) [inline Source/Serilog.Exceptions/Core/ExceptionPropertiesBag.cs:90]: Won't this still silently fail if there are 5 properties with same name?

Comment (krajek) [reply Source/Serilog.Exceptions/Core/ExceptionPropertiesBag.cs:90]: Yes, it still will :-).
Why I did it that way?
a) I would never leave an infinite loop in a production code. Even though it is simple code in our case I am still terrified of infinite loops :-).
b) This is just a "defensive" code mechanism that happens to also "fix" #343. After that is merged I will prepare a second PR where we will actually be taking into account the "new" modifier in restructured classes.
c) After few years of library existence, it is the first time when someone reported a problem with exceptions with redefined properties(1 level of "new" modifiers). I assume 5 levels of "new" modifiers is too crazy for real-world and expect this code to work just fine in practice.

File: Source/Serilog.Exceptions/Core/ExceptionPropertiesBag.cs [hunk 2]
```diff
@@ -56,10 +63,46 @@ public void AddProperty(string key, object? value)
...
+        }
+
+#if !NET5_0
+        
+        private string MakeSureKeyIsUnique(string key)
+        {
+            var i = 0;
+            while (this.properties.ContainsKey(key) && i < AcceptableNumberOfSameNameProperties)
+            {
+                key += "$";
```
Comment (RehanSaeed) [inline Source/Serilog.Exceptions/Core/ExceptionPropertiesBag.cs:100]: Perhaps it would be better to prefix the key with the name of the class the property came from instead e.g.

```
BaseClass.Foo
DerivedClass.Foo
```

This would make the name longer but this is a rare case and it would make it easier to understand which duplicate property came from where.

**Review by RehanSaeed — COMMENTED** [review]
Made a small suggestion.

File: Source/Serilog.Exceptions/Core/ExceptionPropertiesBag.cs (hunk 2 above)
Comment (krajek) [reply Source/Serilog.Exceptions/Core/ExceptionPropertiesBag.cs:100]: That makes sense, agreed, but the `ExceptionPropertiesBag` operates on `string key` already, without the context of where it came from.

In the second PR, we may discuss whether to use that convention or just discard `BaseClass.Foo`.

**Comment by krajek** [comment]
@RehanSaeed can we merge this?

**Comment by RehanSaeed** [comment]
Sorry, will take a look on Monday.

**Comment by krajek** [comment]
> Sorry, will take a look on Monday.

Thanks, in the meantime I will start working on next PR based on this one 👍

File: Source/Serilog.Exceptions/Core/ExceptionPropertiesBag.cs [hunk 3]
```diff
@@ -7,9 +7,16 @@ namespace Serilog.Exceptions.Core
...
+        /// In theory there should not be any properties with same names passed
+        /// but just as a defensive and robustness measure, we allow small amount
+        /// so that library can keep working in case of minor error (or unexpected
+        /// scenario) on the properties provider side.
+        /// </summary>
+        private const int AcceptableNumberOfSameNameProperties = 5;
         private readonly Exception exception;
         private readonly IExceptionPropertyFilter? filter;
-        private readonly Dictionary<string, object?> properties = new();
+        private readonly Dictionary<string, object?> properties = new ();
```
Comment (RehanSaeed) [inline Source/Serilog.Exceptions/Core/ExceptionPropertiesBag.cs:19]: Got some warings because:

> The keyword 'new' should not be followed by a space

**Comment by RehanSaeed** [comment]
@krajek Shall we go with https://github.com/RehanSaeed/Serilog.Exceptions/pull/347 instead and maybe roll all changes into that PR?

**Comment by krajek** [comment]
If you do not care I would rather merge this and then consider #347 separately.
I really am a fan of small targeted pull requests :-).
