### PR TITLE
Generic exception properties filter

### LINKED ISSUE #29: Be able to exclude the StackTrace
It would be nice to be able to exclude the StackTrace because SeriLog already includes that and the duplication can get quite large.

### PR DESCRIPTION
**Pull request by krajek**
This change introduces a generic `IExceptionPropertyFilter`. Implementation of that interface
can be passed to a configuration and then every property of every exception destructured
would go through the filter. 

The filter can be used to solve the problem of duplicated `StackTrace` (fixes #29).

There is also new abstraction `ExceptionPropertiesBag` that replaces passing raw dictionary
of key/value pairs in and out of destructurers. This class introduced a single point of responsibility 
for adding properties, necessary for consistent filtering.

BTW, a new directory named `Core` was added to the main project. `Destructurers` directory
will contain only actual destructurers classes.

### CODE REVIEW

File: Source/Serilog.Exceptions/Core/ExceptionFilterIgnoringByName.cs [hunk 1]
```diff
@@ -0,0 +1,32 @@
+namespace Serilog.Exceptions.Core
+{
+    using System;
+
+    public class ExceptionFilterIgnoringByName : IExceptionPropertyFilter
+    {
+        private readonly string[] propertiesToIgnore;
```
Comment (optical) [inline Source/Serilog.Exceptions/Core/ExceptionFilterIgnoringByName.cs]: This should be a Hashset<string> for faster lookups.

**Comment by optical** [comment]
Worth noting this should be a major version bump since it changes signatures, so is a breaking change.

Will leave this up to @RehanSaeed to review properly :)

File: Source/Serilog.Exceptions/LoggerEnrichmentConfigurationExtensions.cs [hunk 2]
```diff
@@ -22,9 +23,10 @@ public static class LoggerEnrichmentConfigurationExtensions
 
         public static Serilog.LoggerConfiguration WithExceptionDetails(
             this LoggerEnrichmentConfiguration loggerEnrichmentConfiguration,
-            IEnumerable<IExceptionDestructurer> destructurers)
+            IEnumerable<IExceptionDestructurer> destructurers,
+            IExceptionPropertyFilter filter)
```
Comment (optical) [inline Source/Serilog.Exceptions/LoggerEnrichmentConfigurationExtensions.cs]: Perhaps this should be an IEnumerable<IExceptionPropertyFilter> too, or have an overload of the method which accepts either a single or an enumerable. That'd mean consumers aren't forced to implement their own composite IExceptionPropertyFilter implementations in order to chain them up.

File: Source/Serilog.Exceptions/Core/ExceptionFilterIgnoringByName.cs (hunk 1 above)
Comment (krajek) [reply Source/Serilog.Exceptions/Core/ExceptionFilterIgnoringByName.cs]: The array implementation was based on my gut feeling, but your question encouraged me to verify.

| Method |      Mean |     Error |    StdDev |
|---|---|---|---|
| ArrayManualLoop |  6.224 ns | 0.1819 ns | 0.3877 ns |
| HashContains | 22.968 ns | 0.2030 ns | 0.1800 ns |

This is the result of benchmark experiment I did, for the typical case of two ignored properties (`StackTrace` and `TargetSite`).  Up to 6-7 ignored properties array implementation is faster. My assumption is that 2 ignored properties will be typical. I will document this assumption in code.

**Comment by optical** [comment]
Aha, nice to be proven wrong with some benchmarks. That seems like a
reasonable assumption. Documenting that sounds good!

File: Source/Serilog.Exceptions/Core/ExceptionFilterIgnoringByName.cs (hunk 1 above)
Comment (RehanSaeed) [reply Source/Serilog.Exceptions/Core/ExceptionFilterIgnoringByName.cs]: Cool

File: Source/Serilog.Exceptions/Core/ExceptionPropertiesBag.cs [hunk 3]
```diff
@@ -0,0 +1,46 @@
...
+        public IReadOnlyDictionary<string, object> ResultDictionary
+        {
+            get
+            {
+                this.resultsCollected = true;
+                return this.properties;
+            }
+        }
+
+        public void AddProperty(string key, object value)
```
Comment (RehanSaeed) [inline Source/Serilog.Exceptions/Core/ExceptionPropertiesBag.cs]: Lets add a check for null here and throw `ArgumentNullException` since this is a public facing API.

File: Source/Serilog.Exceptions/Core/ExceptionPropertiesBag.cs [hunk 4]
```diff
@@ -0,0 +1,46 @@
...
+        {
+            this.exceptionType = exceptionType;
+            this.filter = filter;
+        }
+
+        public IReadOnlyDictionary<string, object> ResultDictionary
+        {
+            get
+            {
+                this.resultsCollected = true;
```
Comment (RehanSaeed) [inline Source/Serilog.Exceptions/Core/ExceptionPropertiesBag.cs]: Setting this flag is kind of a side effect, I'm wondering if we should add an explicit method for this.

File: Source/Serilog.Exceptions/LoggerEnrichmentConfigurationExtensions.cs (hunk 2 above)
Comment (RehanSaeed) [reply Source/Serilog.Exceptions/LoggerEnrichmentConfigurationExtensions.cs]: I'm wondering the same.

File: Source/Serilog.Exceptions/Core/ExceptionEnricher.cs [hunk 5]
```diff
@@ -57,9 +63,9 @@ public void Enrich(LogEvent logEvent, ILogEventPropertyFactory propertyFactory)
             }
         }
 
-        private Dictionary<string, object> DestructureException(Exception exception)
+        private IReadOnlyDictionary<string, object> DestructureException(Exception exception)
```
Comment (RehanSaeed) [inline Source/Serilog.Exceptions/Core/ExceptionEnricher.cs]: `IReadOnlyDictionary` is good.

File: Source/Serilog.Exceptions/Core/ExceptionFilterIgnoringByName.cs [hunk 6]
```diff
@@ -0,0 +1,42 @@
...
+    public class ExceptionFilterIgnoringByName : IExceptionPropertyFilter
+    {
+        /// <summary>
+        /// The usage of array instead of HashSet is dictated by the assumption
+        /// that there will be only small number of properties to ignore and for such
+        /// case array is much faster than HashSet.
+        /// </summary>
+        private readonly string[] propertiesToIgnore;
+
+        public ExceptionFilterIgnoringByName(string[] propertiesToIgnore)
```
Comment (RehanSaeed) [inline Source/Serilog.Exceptions/Core/ExceptionFilterIgnoringByName.cs]: Perhaps provide a `params` constructor, along with an `IEnumerable<T>` one too.

File: Source/Serilog.Exceptions/Core/IExceptionPropertyFilter.cs [hunk 7]
```diff
@@ -0,0 +1,9 @@
+namespace Serilog.Exceptions.Core
+{
+    using System;
+
+    public interface IExceptionPropertyFilter
+    {
+        bool ShouldPropertyBeFiltered(Type exceptionType, string propertyName, object value);
```
Comment (RehanSaeed) [inline Source/Serilog.Exceptions/Core/IExceptionPropertyFilter.cs]: How about `CanAddProperty`?

File: Source/Serilog.Exceptions/LoggerEnrichmentConfigurationExtensions.cs (hunk 2 above)
Comment (RehanSaeed) [reply Source/Serilog.Exceptions/LoggerEnrichmentConfigurationExtensions.cs]: I'm wondering the same. The alternative would be providing some kind of filter that accepts and uses multiple filters itself.

File: Source/Serilog.Exceptions/Core/ExceptionFilterIgnoringByName.cs (hunk 6 above)
Comment (krajek) [reply Source/Serilog.Exceptions/Core/ExceptionFilterIgnoringByName.cs]: Done

File: Source/Serilog.Exceptions/Core/ExceptionPropertiesBag.cs (hunk 3 above)
Comment (krajek) [reply Source/Serilog.Exceptions/Core/ExceptionPropertiesBag.cs]: Done

File: Source/Serilog.Exceptions/Core/ExceptionPropertiesBag.cs (hunk 4 above)
Comment (krajek) [reply Source/Serilog.Exceptions/Core/ExceptionPropertiesBag.cs]: Done

File: Source/Serilog.Exceptions/LoggerEnrichmentConfigurationExtensions.cs (hunk 2 above)
Comment (krajek) [reply Source/Serilog.Exceptions/LoggerEnrichmentConfigurationExtensions.cs]: Because a single interface is so flexible, I implemented CompositeExceptionPropertyFilter.

**Comment by krajek** [comment]
I implemented most of the suggestions and provided documentation in README.md.
Anything else that comes to your mind before the merge?

BTW, I do not your plans, but please do not release next version on the spot, I have few more ideas for improvements in other parts.

File: Source/Serilog.Exceptions/Filters/ExceptionFilterIgnoringByName.cs [hunk 8]
```diff
@@ -0,0 +1,42 @@
+namespace Serilog.Exceptions.Filters
+{
+    using System;
+
+    /// <summary>
+    /// Filters the exception properties based only on their name. If exception property
+    /// matches any of provided property names, exception property is ignored altogether.
+    /// Comparison method is exact case-sensitive.
+    /// </summary>
+    public class ExceptionFilterIgnoringByName : IExceptionPropertyFilter
```
Comment (RehanSaeed) [inline Source/Serilog.Exceptions/Filters/ExceptionFilterIgnoringByName.cs]: I suggest reversing the naming to `IgnorePropertyByNameExceptionFilter` or perhaps `IgnoreNamedPropertyExceptionFilter`.

File: Source/Serilog.Exceptions/Filters/IExceptionPropertyFilter.cs [hunk 9]
```diff
@@ -0,0 +1,22 @@
...
+    {
+        /// <summary>
+        /// Called after the property was discovered and destructured but
+        /// just before it is added to results.
+        /// </summary>
+        /// <param name="exceptionType">Type of the exception for which properties are filtered</param>
+        /// <param name="propertyName">Name of the property</param>
+        /// <param name="value">Destructured value of the property </param>
+        /// <returns>Boolean flag indicating whether property will be rejected</returns>
+        bool ShouldPropertyBeFiltered(Type exceptionType, string propertyName, object value);
```
Comment (RehanSaeed) [inline Source/Serilog.Exceptions/Filters/IExceptionPropertyFilter.cs]: I still like `CanAddProperty`

File: Source/Serilog.Exceptions/LoggerEnrichmentConfigurationExtensions.cs (hunk 2 above)
Comment (RehanSaeed) [reply Source/Serilog.Exceptions/LoggerEnrichmentConfigurationExtensions.cs]: I've seen it done both ways in public API's. If it was `IEnumerable`, we could also add a `params` constructor. On the other had `CompositeExceptionPropertyFilter` makes it pay for play. I slightly prefer the former.

File: Source/Serilog.Exceptions/Core/ExceptionEnricher.cs [hunk 10]
```diff
@@ -20,22 +22,38 @@ public sealed class ExceptionEnricher : ILogEventEnricher
             new ReflectionTypeLoadExceptionDestructurer()
         };
 
+        public static readonly IExceptionPropertyFilter FilterIgnoringStackTraceAndTargetId =
```
Comment (RehanSaeed) [inline Source/Serilog.Exceptions/Core/ExceptionEnricher.cs]: Reverse the naming again to `IgnoreStackTraceAndTargetIdExceptionFilter`

File: Source/Serilog.Exceptions/Core/ExceptionEnricher.cs [hunk 11]
```diff
@@ -20,22 +22,38 @@ public sealed class ExceptionEnricher : ILogEventEnricher
...
+
+#if NET45
```
Comment (RehanSaeed) [inline Source/Serilog.Exceptions/Core/ExceptionEnricher.cs]: Perhaps we should move these common filters to their own `ExceptionFilter` static class. Perhaps we should do the same with the destructurers.

File: Source/Serilog.Exceptions/Core/ExceptionPropertiesBag.cs [hunk 12]
```diff
@@ -0,0 +1,49 @@
...
+        }
+
+        public void AddProperty(string key, object value)
+        {
+            if (key == null)
+            {
+                throw new ArgumentNullException(nameof(key), "Cannot add exception property without a key");
+            }
+
+            if (this.resultsCollected)
```
Comment (RehanSaeed) [inline Source/Serilog.Exceptions/Core/ExceptionPropertiesBag.cs]: Is there a reason for us to stop adding/removing properties at runtime?

File: Source/Serilog.Exceptions/Core/ExceptionEnricher.cs (hunk 10 above)
Comment (krajek) [reply Source/Serilog.Exceptions/Core/ExceptionEnricher.cs]: Done.

File: Source/Serilog.Exceptions/Core/ExceptionEnricher.cs (hunk 11 above)
Comment (krajek) [reply Source/Serilog.Exceptions/Core/ExceptionEnricher.cs]: It would contain just one property so I would keep it the way it is. Additionally, moving destructurers property would be a minor backwards-compatibility break.

File: Source/Serilog.Exceptions/Core/ExceptionPropertiesBag.cs (hunk 12 above)
Comment (krajek) [reply Source/Serilog.Exceptions/Core/ExceptionPropertiesBag.cs]: It is just an application of the fail-fast principle. If somebody is modifying result after it was collected and used in the resulting structure, there is something seriously wrong.

File: Source/Serilog.Exceptions/Filters/ExceptionFilterIgnoringByName.cs (hunk 8 above)
Comment (krajek) [reply Source/Serilog.Exceptions/Filters/ExceptionFilterIgnoringByName.cs]: Done

File: Source/Serilog.Exceptions/Filters/IExceptionPropertyFilter.cs (hunk 9 above)
Comment (krajek) [reply Source/Serilog.Exceptions/Filters/IExceptionPropertyFilter.cs]: Could you elaborate a little bit? I am not saying that is a bad name, it's just my gut feeling that is better to phrase the method so that it specifies properties that should be excluded(like `ShouldBeFiltered` or `ShouldBeRejected`) then for it to specify properties to be added(like CanAddProperty or ShouldBeAdded).

File: Source/Serilog.Exceptions/Core/ExceptionPropertiesBag.cs (hunk 12 above)
Comment (krajek) [reply Source/Serilog.Exceptions/Core/ExceptionPropertiesBag.cs]: I added a comment to document my thinking behind this invariant checking.

**Comment by krajek** [comment]
Yeah, of course, other idea's implementations will come in their own PR's.

**Comment by RehanSaeed** [comment]
Ok, seems on track.

File: Source/Serilog.Exceptions/Filters/CompositeExceptionPropertyFilter.cs [hunk 13]
```diff
@@ -0,0 +1,57 @@
...
+                    throw new ArgumentException(
+                        $"Cannot create composite exception properties filter, because filter at index {i} is null",
+                        nameof(filters));
+                }
+            }
+
+            this.filters = filters;
+        }
+
+        public bool ShouldPropertyBeFiltered(Exception exception, string propertyName, object value)
```
Comment (RehanSaeed) [inline Source/Serilog.Exceptions/Filters/CompositeExceptionPropertyFilter.cs]: Npt sure why my comment is disappearing. How about `CanAddProperty`.

Comment (krajek) [reply Source/Serilog.Exceptions/Filters/CompositeExceptionPropertyFilter.cs]: Regarding disappearing comments: they are present, but they are collapsed. You need to click 'Show outdated' to view them. 

I will repeat my previous response:
  Could you elaborate a little bit? I am not saying that is a bad name, it's just my gut feeling that 
  is better to phrase the method so that it specifies properties that should be excluded(like 
  ShouldBeFiltered or ShouldBeRejected) then for it to specify properties to be added(like 
  CanAddProperty or ShouldBeAdded).

Comment (RehanSaeed) [reply Source/Serilog.Exceptions/Filters/CompositeExceptionPropertyFilter.cs]: Fair enough.

**Comment by RehanSaeed** [comment]
Happy to merge? I'll upgrade the major version and do a release soon.

**Comment by krajek** [comment]
Yes, LGTM. Thanks a lot for the reviews, lots of good suggestions!

Regarding major version: of course, it is your call, but just letting you know that shortly after merge I will work on two or three PRs more. 
I am only mentioning this to avoid major release week after the previous major

**Comment by RehanSaeed** [comment]
Major version because it breaks the public API surface a bit. It would be interesting to hear your other ideas, feel free to raise an issue to discuss. If they also break the API surface, perhaps we could batch the changes together into a single major version update.
